/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddComponent: typeof import('./src/components/mailView/AddComponent.vue')['default']
    BarcharComponent: typeof import('./src/components/BarcharComponent.vue')['default']
    CityBarcharComponent: typeof import('./src/components/CityBarcharComponent.vue')['default']
    EditComponent: typeof import('./src/components/mailView/editComponent.vue')['default']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    FourEchartComponent1: typeof import('./src/components/FourEchart/FourEchartComponent1.vue')['default']
    FourEchartComponent2: typeof import('./src/components/FourEchart/FourEchartComponent2.vue')['default']
    FrontLayout: typeof import('./src/components/FrontLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    OutputExcel: typeof import('./src/components/OutputExcel.vue')['default']
    PageFourView: typeof import('./src/components/frontpage/PageFourView.vue')['default']
    PageOneView: typeof import('./src/components/frontpage/PageOneView.vue')['default']
    PageThreeView: typeof import('./src/components/frontpage/PageThreeView.vue')['default']
    PageTwoView: typeof import('./src/components/frontpage/PageTwoView.vue')['default']
    PiechartComponent: typeof import('./src/components/PiechartComponent.vue')['default']
    RolepageAlert: typeof import('./src/components/RolepageAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendComponent: typeof import('./src/components/mailView/SendComponent.vue')['default']
    SendComponent2: typeof import('./src/components/mailView/SendComponent2.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ThreeViewCategoryComponent: typeof import('./src/components/ThreePiechart/ThreeViewCategoryComponent.vue')['default']
    ThreeViewPiechartComponent: typeof import('./src/components/ThreePiechart/ThreeViewPiechartComponent.vue')['default']
    TreecharComponent: typeof import('./src/components/TreecharComponent.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
